version: 2.1
jobs:
  Lint:
    docker:
      - image: cimg/go:1.13
    steps:
      - checkout
      - run: go vet -v -t -d ./...
      - run : go fmt -v -t -d ./...
  Test:
    docker:
      - image: cimg/go:1.13
    steps:
      - checkout
      - run: go test -v ./...
  Build:
    docker:
      - image: cimg/go:1.13
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go build -o appdemo
      - persist_to_workspace:
          root: .
          paths:
            - ./appdemo
  Publish:
    docker:
      - image: cimg/go:1.13
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run: |
          cp /tmp/workspace/appdemo .
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t adefemi171/appdemo:$TAG .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push adefemi171/appdemo:$TAG

workflows:
  version: 2
  Test-Build-Publish:
    jobs:
      - Lint
      - Test:
          requires:
            - Lint
      - Build:
          requires:
            - Test
      - Publish:
          requires:
            - Build    